version: '3.7'

services:
    mongodb:
        image: mongo:4.4.3
        container_name: nest-js-image-api
        restart: always
        environment:
            #MONGO_INITDB_ROOT_USERNAME: <admin-user>
            #MONGO_INITDB_ROOT_PASSWORD: <admin-password>
            MONGO_INITDB_DATABASE: imageapi
        ports:
            - 27017:27017
        #volumes:
            #- ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
